### ISSUE TITLE
Backslashses in file names

### ISSUE THREAD

**Issue by Eneroth3** [thomthom/skippy#23]
When using Windows-style backslashes for  instead of forward slashes to install a local library I got a rather cryptic error message. Perhaps both styles could be accepted?

**Comment by thomthom** [comment]
What's the error message?

**Comment by Eneroth3** [comment]
![2018-01-12_17h59_55](https://user-images.githubusercontent.com/5631725/34904575-c3108e46-f848-11e7-9154-fac4f0ed288d.png)

**Comment by thomthom** [comment]
Ah, I see what's going on. And the same path, just with forward slashes, works fine?

(Btw, in the Windows command window you can copy text by right-clicking and choosing Mark. I personally use Cmder instead as it add easier copy+paste)

**Comment by Eneroth3** [comment]
With forward slashes it works great! I simply copied the path from the address bar in explorer so I wouldn't have to write the whole thing myself.

( should probably look into Cmder too, but one new thing at a time)

**Comment by thomthom** [comment]
Then this fix should be as easy as making sure I normalize the source input with forward slashes. Thanks for testing out and reporting.

**Comment by thomthom** [comment]
I'll push a new release later this weekend. But now - breakfast!
