### ISSUE TITLE
Ruby exception from unconventional SketchUp version

### ISSUE THREAD

**Issue by Eneroth3** [thomthom/skippy#41]
Unconventional SketchUp folder names with text after the version number causes a Ruby exception on this line.

https://github.com/thomthom/skippy/blob/e3ec2101d5d862877747cde2b14806d2dcc84751/lib/skippy/os/win.rb#L31

Either the regex needs to be more generous to support these formats, or it should be checked if there is a match at all before calling [], preferably with a warning saying it's an unexpected name.

This affects the debugger in VSCode which uses Skippy to list SketchUp installs.

**Comment by Postur** [comment]
This has been fixed with this [commit](https://github.com/thomthom/skippy/commit/61e5ee91f7531d98227906bf81c06ea1d0b62884)
